name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2, 8.3]
        laravel: [10.*, 11.*, 12.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          -   laravel: 10.*
              testbench: 8.*
          -   laravel: 11.*
              testbench: 9.*
          -   laravel: 12.*
              testbench: 10.*
        exclude:
          -   laravel: 11.*
              php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v4

      -   name: Install SQLite 3
          run: |
            sudo apt-get update
            sudo apt-get install sqlite3

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
            coverage: none

      -   name: Install dependencies
          run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:>=2.62.1" --no-interaction --no-update
            composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      -   name: Setup Problem Matches
          run: |
            echo "::add-matcher::${{ runner.tool_cache }}/php.json"
            echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      -   name: Execute tests
          run: vendor/bin/pest
